# Generated by Django 6.0.5 on 2026-06-05 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('coaching_cues', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('movement_pattern', models.CharField(choices=[('cardio', 'Cardio'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('push', 'Push'), ('pull', 'Pull'), ('core', 'Core'), ('arms', 'Arms'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps_min', models.PositiveSmallIntegerField(default=8)),
                ('default_reps_max', models.PositiveSmallIntegerField(default=12)),
                ('default_rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('is_bodyweight', models.BooleanField(default=False)),
                ('is_unilateral', models.BooleanField(default=False, help_text='True if the exercise is performed separately for left/right side.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='workouts.equipment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('stabilizer', 'Stabilizer')], default='primary', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscles', to='workouts.exercise')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_muscles', to='workouts.musclegroup')),
            ],
            options={
                'ordering': ['exercise__name', 'role', 'muscle_group__name'],
                'unique_together': {('exercise', 'muscle_group')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='workouts.ExerciseMuscle', to='workouts.musclegroup'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('generation_type', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='generated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('target_sets', models.PositiveSmallIntegerField(default=3)),
                ('target_reps_min', models.PositiveSmallIntegerField(default=8)),
                ('target_reps_max', models.PositiveSmallIntegerField(default=12)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('is_completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_exercises', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['session', 'position'],
                'unique_together': {('session', 'position')},
            },
        ),
        migrations.CreateModel(
            name='UserExerciseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('best_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preferred_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False, help_text='If true, this exercise should not be generated for this user.')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'exercise__name'],
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Rate of perceived exertion, 1-10.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_completed', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_results', to='workouts.workoutsessionexercise')),
            ],
            options={
                'ordering': ['session_exercise', 'set_number'],
                'unique_together': {('session_exercise', 'set_number')},
            },
        ),
    ]
