# Generated by Django 6.0.5 on 2026-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionexercise',
            name='block_type',
            field=models.CharField(choices=[('warmup', 'Bemelegítés'), ('circuit', 'Köredzés'), ('cooldown', 'Levezetés')], default='circuit', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Kezdő'), ('intermediate', 'Középhaladó'), ('advanced', 'Haladó')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(choices=[('cardio', 'Kardió'), ('squat', 'Guggolás'), ('hinge', 'Csípőhajlítás / hátsó lánc'), ('push', 'Nyomás'), ('pull', 'Húzás'), ('core', 'Törzs'), ('arms', 'Kar'), ('mobility', 'Mobilitás'), ('other', 'Egyéb')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercisemuscle',
            name='role',
            field=models.CharField(choices=[('primary', 'Elsődleges'), ('secondary', 'Másodlagos'), ('stabilizer', 'Stabilizáló')], default='primary', max_length=20),
        ),
    ]
