# Generated by Django 6.0.5 on 2026-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutsessionexercise_block_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='circuit_exercise_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='circuit_rounds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_profile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
