# Generated by Django 6.0.5 on 2026-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_exercise_movement_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(choices=[('cardio', 'Kardió'), ('squat', 'Guggolás'), ('hinge', 'Csípőhajlítás / hátsó lánc'), ('push', 'Nyomás'), ('pull', 'Húzás'), ('core', 'Törzs'), ('arms', 'Kar'), ('mobility', 'Mobilitás'), ('stretching', 'Nyújtás'), ('aerobic_video', 'Aerobic videó'), ('other', 'Egyéb')], default='other', max_length=30),
        ),
    ]
