# Generated by Django 6.0.5 on 2026-05-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=255)),
                ('target_text', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('word', 'Szó'), ('phrase', 'Kifejezés'), ('sentence', 'Mondat')], default='word', max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='vocabulary.deck')),
            ],
            options={
                'ordering': ['source_text'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_decks', to='vocabulary.language'),
        ),
        migrations.AddField(
            model_name='deck',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_decks', to='vocabulary.language'),
        ),
    ]
