# Generated by Django 6.0.5 on 2026-05-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_practiceattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('source-to-target', 'Forrás → Cél'), ('target-to-source', 'Cél → Forrás')], max_length=30)),
                ('requested_question_count', models.PositiveIntegerField()),
                ('first_round_question_count', models.PositiveIntegerField()),
                ('first_round_correct_count', models.PositiveIntegerField()),
                ('first_round_wrong_count', models.PositiveIntegerField()),
                ('accuracy_percent', models.PositiveIntegerField()),
                ('repeated_wrong_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_session_results', to='vocabulary.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_session_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
