# Generated by Django 6.0.5 on 2026-05-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_practicesessionresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeAttempt',
        ),
    ]
